### ISSUE TITLE
How to get information in English

### ISSUE THREAD

**Issue by mumenma** [BlockBeatsOfficial/RSS#1]

**Comment by BlockBeatsOfficial** [comment]
Coming soon, thanks.

**Comment by mumenma** [comment]
How much longer do we need?

**Comment by BlockBeatsOfficial** [comment]
The update has been completed. Please refer to the documentation for specific instructions on how to retrieve multiple languages using RSS and RESTful API. Thank you.

**Comment by mumenma** [comment]
thanks
